#Requires -Version 5.1
param(
  [string]$InstallDir = "$env:USERPROFILE\hippocampus",
  [switch]$NoModels
)

$ErrorActionPreference = "Stop"

function Write-Step  { Write-Host "  ▶ $args" -ForegroundColor Cyan }
function Write-Ok    { Write-Host "  ✓ $args" -ForegroundColor Green }
function Write-Warn  { Write-Host "  ⚠ $args" -ForegroundColor Yellow }
function Write-Fatal { Write-Host "  ✗ $args" -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "  HIPPOCAMPUS — Local AI Memory System" -ForegroundColor White
Write-Host "  Installer for Windows" -ForegroundColor Gray
Write-Host ""

# ── Check Docker ──────────────────────────────────────────────────────────────
Write-Step "Checking Docker..."
try {
  $dockerVersion = & docker --version 2>&1
  if ($LASTEXITCODE -ne 0) { throw "Docker returned non-zero" }
  Write-Ok "Docker: $dockerVersion"
} catch {
  Write-Warn "Docker not found. Opening Docker Desktop download page..."
  Start-Process "https://docker.com/products/docker-desktop"
  Write-Fatal "Please install Docker Desktop and re-run this installer."
}

# ── Check Docker Compose v2 ───────────────────────────────────────────────────
Write-Step "Checking Docker Compose..."
try {
  $composeVersion = & docker compose version 2>&1
  if ($LASTEXITCODE -ne 0) { throw "Docker Compose v2 not found" }
  Write-Ok "Compose: $composeVersion"
} catch {
  Write-Fatal "Docker Compose v2 not found. Please update Docker Desktop."
}

# ── Create directories ────────────────────────────────────────────────────────
Write-Step "Creating install directory: $InstallDir"
$dirs = @(
  "data\qdrant", "data\ollama", "data\hippocampus",
  "data\models", "data\piper-voices", "uploads"
)
foreach ($d in $dirs) {
  New-Item -ItemType Directory -Force -Path "$InstallDir\$d" | Out-Null
}
Write-Ok "Directories created"

# ── Write docker-compose.yml ──────────────────────────────────────────────────
Write-Step "Writing configuration..."
$composeDest = "$InstallDir\docker-compose.yml"
if (-not (Test-Path $composeDest)) {
  $composeSrc = Join-Path $PSScriptRoot "docker-compose.yml"
  if (Test-Path $composeSrc) {
    Copy-Item $composeSrc $composeDest
  } else {
    # Inline fallback if running from a downloaded script
    @'
# Generated by Hippocampus installer
services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: hippocampus-qdrant
    restart: unless-stopped
    ports: ["6333:6333", "6334:6334"]
    volumes: ["./data/qdrant:/qdrant/storage"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/6333'"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: hippocampus-ollama
    restart: unless-stopped
    ports: ["11434:11434"]
    volumes: ["./data/ollama:/root/.ollama"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/11434'"]
      interval: 15s
      timeout: 5s
      retries: 5

  hippocampus:
    image: ghcr.io/yourusername/hippocampus:latest
    container_name: hippocampus-app
    restart: unless-stopped
    ports: ["50051:50051", "3001:3001"]
    volumes:
      - ./data/hippocampus:/app/data
      - ./data/models:/app/models
      - ./data/piper-voices:/app/piper-voices
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - GRPC_PORT=50051
      - HTTP_PORT=3001
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_CONCURRENCY=8
      - CHUNK_STRATEGY=fast
      - WHISPER_MODEL=small
      - VISION_MODEL=moondream
      - DB_PATH=/app/data/hippocampus.db
      - OVERVIEWS_DIR=/app/data/overviews
      - TRANSFORMERS_CACHE=/app/models
      - CUDA_VISIBLE_DEVICES=-1
      - PIPER_VOICES_DIR=/app/piper-voices
    depends_on:
      qdrant: {condition: service_healthy}
      ollama: {condition: service_healthy}
'@ | Set-Content $composeDest
  }
  Write-Ok "docker-compose.yml written"
} else {
  Write-Warn "docker-compose.yml already exists — skipping (delete to regenerate)"
}

# ── Write docker-compose.cli.yml ──────────────────────────────────────────────
$cliComposeDest = "$InstallDir\docker-compose.cli.yml"
if (-not (Test-Path $cliComposeDest)) {
  @'
services:
  hippocampus:
    entrypoint: ["node", "dist/cli/cli.js"]
    restart: "no"
    ports: []
'@ | Set-Content $cliComposeDest
}

# ── Pull images ───────────────────────────────────────────────────────────────
Write-Step "Pulling Docker images (this may take several minutes)..."
Set-Location $InstallDir
& docker compose pull
if ($LASTEXITCODE -ne 0) { Write-Fatal "Failed to pull Docker images." }

# ── Pull models ───────────────────────────────────────────────────────────────
if (-not $NoModels) {
  Write-Step "Pulling AI models (phi3:mini ~2.3GB, moondream ~1.7GB)..."
  & docker compose up -d ollama
  # Wait for Ollama to be ready
  $retries = 0
  do {
    Start-Sleep 3
    $ready = & docker exec hippocampus-ollama ollama list 2>&1
    $retries++
  } while ($LASTEXITCODE -ne 0 -and $retries -lt 20)

  & docker exec hippocampus-ollama ollama pull phi3:mini
  & docker exec hippocampus-ollama ollama pull moondream
  & docker compose stop ollama
  Write-Ok "AI models downloaded"
}

# ── Install CLI wrapper ───────────────────────────────────────────────────────
Write-Step "Installing CLI..."
$cliDir = "$env:USERPROFILE\AppData\Local\Programs\hippocampus"
New-Item -ItemType Directory -Force -Path $cliDir | Out-Null

$escapedDir = $InstallDir -replace '\\', '\\'
$cliScript = "@echo off`r`ncd /d `"$InstallDir`"`r`ndocker compose -f docker-compose.yml -f docker-compose.cli.yml run --rm hippocampus %*`r`n"
[System.IO.File]::WriteAllText("$cliDir\hippocampus.bat", $cliScript)

# Add to user PATH if not already there
$userPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($userPath -notlike "*$cliDir*") {
  [Environment]::SetEnvironmentVariable("PATH", "$userPath;$cliDir", "User")
  Write-Warn "Added $cliDir to PATH — restart your terminal for it to take effect"
}
Write-Ok "CLI installed: hippocampus.bat"

# ── Start ─────────────────────────────────────────────────────────────────────
Write-Step "Starting Hippocampus..."
Set-Location $InstallDir
& docker compose up -d
if ($LASTEXITCODE -ne 0) { Write-Fatal "Failed to start services." }

Write-Host ""
Write-Host "  ✓ Hippocampus installed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "    Dashboard:  http://localhost:3001" -ForegroundColor White
Write-Host "    CLI:        hippocampus ingest C:\path\to\file.pdf" -ForegroundColor White
Write-Host "    Stop:       cd $InstallDir && docker compose down" -ForegroundColor Gray
Write-Host "    Logs:       cd $InstallDir && docker compose logs -f hippocampus" -ForegroundColor Gray
Write-Host ""
