#!/usr/bin/env bash
set -euo pipefail

HIPPOCAMPUS_DIR="${HIPPOCAMPUS_DIR:-$HOME/hippocampus}"
HIPPOCAMPUS_VERSION="${HIPPOCAMPUS_VERSION:-latest}"

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

log()  { echo -e "${BLUE}▶${RESET} $*"; }
ok()   { echo -e "${GREEN}✓${RESET} $*"; }
warn() { echo -e "${YELLOW}⚠${RESET} $*"; }
die()  { echo -e "${RED}✗${RESET} $*" >&2; exit 1; }

echo -e "${BOLD}"
echo "  ██╗  ██╗██╗██████╗ ██████╗  ██████╗  ██████╗ █████╗ ███╗   ███╗██████╗ ██╗   ██╗███████╗"
echo "  ██║  ██║██║██╔══██╗██╔══██╗██╔═══██╗██╔════╝██╔══██╗████╗ ████║██╔══██╗██║   ██║██╔════╝"
echo "  ███████║██║██████╔╝██████╔╝██║   ██║██║     ███████║██╔████╔██║██████╔╝██║   ██║███████╗"
echo "  ██╔══██║██║██╔═══╝ ██╔═══╝ ██║   ██║██║     ██╔══██║██║╚██╔╝██║██╔═══╝ ██║   ██║╚════██║"
echo "  ██║  ██║██║██║     ██║     ╚██████╔╝╚██████╗██║  ██║██║ ╚═╝ ██║██║     ╚██████╔╝███████║"
echo "  ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝      ╚═════╝  ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝      ╚═════╝ ╚══════╝"
echo -e "${RESET}"
echo "  Local AI Memory System — Installer"
echo ""

# ── Detect OS ────────────────────────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
  Linux)  PLATFORM="linux" ;;
  Darwin) PLATFORM="macos" ;;
  *)      die "Unsupported OS: $OS. Use install.ps1 on Windows." ;;
esac

log "Platform: $PLATFORM ($ARCH)"

# ── Check / install Docker ────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  warn "Docker not found. Installing..."
  case "$PLATFORM" in
    linux)
      curl -fsSL https://get.docker.com | sh
      sudo usermod -aG docker "$USER"
      warn "Docker installed. You may need to log out and back in for group changes."
      ;;
    macos)
      die "Docker not found. Please install Docker Desktop from https://docker.com/products/docker-desktop"
      ;;
  esac
else
  ok "Docker $(docker --version | cut -d' ' -f3 | tr -d ',')"
fi

# ── Check Docker Compose ──────────────────────────────────────────────────────
if ! docker compose version &>/dev/null; then
  die "Docker Compose v2 not found. Please update Docker."
fi
ok "Docker Compose $(docker compose version --short)"

# ── Create install directory ──────────────────────────────────────────────────
log "Installing to $HIPPOCAMPUS_DIR"
mkdir -p "$HIPPOCAMPUS_DIR"/{data/qdrant,data/ollama,data/hippocampus,data/models,data/piper-voices,uploads}

# ── Write docker-compose.yml ──────────────────────────────────────────────────
log "Writing docker-compose.yml..."

# Only write if it doesn't exist or explicitly upgrading
if [[ -f "$HIPPOCAMPUS_DIR/docker-compose.yml" ]]; then
  warn "docker-compose.yml already exists — skipping (delete to regenerate)"
else
cat > "$HIPPOCAMPUS_DIR/docker-compose.yml" << 'COMPOSE'
# Generated by Hippocampus installer — edit to customise your installation
services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: hippocampus-qdrant
    restart: unless-stopped
    ports: ["6333:6333", "6334:6334"]
    volumes: ["./data/qdrant:/qdrant/storage"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/6333'"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: hippocampus-ollama
    restart: unless-stopped
    ports: ["11434:11434"]
    volumes: ["./data/ollama:/root/.ollama"]
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/11434'"]
      interval: 15s
      timeout: 5s
      retries: 5

  hippocampus:
    image: ghcr.io/yourusername/hippocampus:latest
    container_name: hippocampus-app
    restart: unless-stopped
    ports: ["50051:50051", "3001:3001"]
    volumes:
      - ./data/hippocampus:/app/data
      - ./data/models:/app/models
      - ./data/piper-voices:/app/piper-voices
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - GRPC_PORT=50051
      - HTTP_PORT=3001
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_CONCURRENCY=8
      - CHUNK_STRATEGY=fast
      - WHISPER_MODEL=small
      - VISION_MODEL=moondream
      - KEYFRAME_INTERVAL=60
      - AUDIO_CHUNK_MINUTES=2
      - DB_PATH=/app/data/hippocampus.db
      - OVERVIEWS_DIR=/app/data/overviews
      - TRANSFORMERS_CACHE=/app/models
      - CUDA_VISIBLE_DEVICES=-1
      - PIPER_VOICES_DIR=/app/piper-voices
    depends_on:
      qdrant: {condition: service_healthy}
      ollama: {condition: service_healthy}

  ollama-pull:
    image: ollama/ollama:latest
    container_name: hippocampus-ollama-pull
    volumes: ["./data/ollama:/root/.ollama"]
    entrypoint: >
      sh -c "
        ollama pull phi3:mini &&
        ollama pull moondream &&
        echo '✅ Models ready'
      "
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama: {condition: service_healthy}
    profiles: [setup]
COMPOSE
  ok "docker-compose.yml written"
fi

# ── Write docker-compose.cli.yml ──────────────────────────────────────────────
if [[ ! -f "$HIPPOCAMPUS_DIR/docker-compose.cli.yml" ]]; then
cat > "$HIPPOCAMPUS_DIR/docker-compose.cli.yml" << 'CLICLI'
services:
  hippocampus:
    entrypoint: ["node", "dist/cli/cli.js"]
    restart: "no"
    ports: []
CLICLI
  ok "docker-compose.cli.yml written"
fi

# ── Pull images ───────────────────────────────────────────────────────────────
log "Pulling Docker images (this may take a few minutes)..."
cd "$HIPPOCAMPUS_DIR"
docker compose pull

# ── Pull Ollama models ────────────────────────────────────────────────────────
log "Pulling AI models (phi3:mini ~2.3GB, moondream ~1.7GB)..."
docker compose up -d ollama
# Wait for Ollama to be ready
for i in $(seq 1 30); do
  if docker exec hippocampus-ollama ollama list &>/dev/null; then break; fi
  sleep 2
done
docker exec hippocampus-ollama ollama pull phi3:mini
docker exec hippocampus-ollama ollama pull moondream
docker compose stop ollama

# ── Install CLI wrapper ───────────────────────────────────────────────────────
CLI_SCRIPT="$HOME/.local/bin/hippocampus"
mkdir -p "$HOME/.local/bin"

cat > "$CLI_SCRIPT" << CLISCRIPT
#!/usr/bin/env bash
cd "$HIPPOCAMPUS_DIR"
docker compose -f docker-compose.yml -f docker-compose.cli.yml run --rm hippocampus "\$@"
CLISCRIPT
chmod +x "$CLI_SCRIPT"

# Add to PATH if not already there
SHELL_RC=""
case "${SHELL:-}" in
  */zsh)  SHELL_RC="$HOME/.zshrc" ;;
  */bash) SHELL_RC="$HOME/.bashrc" ;;
esac

if [[ -n "$SHELL_RC" ]] && ! grep -q '.local/bin' "$SHELL_RC" 2>/dev/null; then
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$SHELL_RC"
  warn "Added ~/.local/bin to PATH in $SHELL_RC — restart your shell or run: source $SHELL_RC"
fi

ok "CLI installed: hippocampus"

# ── Start services ────────────────────────────────────────────────────────────
log "Starting Hippocampus..."
cd "$HIPPOCAMPUS_DIR"
docker compose up -d

echo ""
echo -e "${GREEN}${BOLD}✓ Hippocampus installed successfully!${RESET}"
echo ""
echo "  Dashboard:  http://localhost:3001"
echo "  CLI:        hippocampus ingest /path/to/file.pdf"
echo "  Stop:       cd $HIPPOCAMPUS_DIR && docker compose down"
echo "  Logs:       cd $HIPPOCAMPUS_DIR && docker compose logs -f hippocampus"
echo ""
